
name: Admin Update Users

on:
  workflow_dispatch:
    inputs:
      data:
        description: 'Updated users.json content (base64-encoded)'
        required: true

jobs:
  update-users:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Decode and write users.json
        run: |
          echo "${{ github.event.inputs.data }}" | base64 -d > users.json

      - name: Commit and push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add users.json
          git commit -m "Update users.json"
          git push
